<template>
    <article class="blog-article">
        <h1>Journey to the Statehouse</h1>
        <p>Hello there.  Thank you for joining me on this journey toward the Ohio Statehouse.  The first question you are probably asking is what movitaved me to go on this journey?  I will tell you that it all began when I pulled up to my polling place in 2022 to vote for my district Ohio Statehouse rep.  When I pulled into the location I was bombarded with a group of volunteers handing out flyers about their candidate.  This was the first time I had ever heard anything of Munira Abdullahi.</p>
        <p>I had already made up my mind where my vote would go despite receiving this flyer.  I went inside the polling place and expressed my concern that the volunteers may have been handing out literature too close to the polling location.  My concern was dismissed by the poll worker.  I went inside to the voting booth and when I looked at the ballot for my district there was only one choice.  It was this person I had never heard of before.  There were no other candidates from any other party.</p>  I found this to be disheartening because it meant government in my local area might be broken.  No one should be appointed to an office unopposed before a voter walks into the voting booth, but that was what happened in my district in 2022.  Strangely, I have found since that of Franklin County's 12 districts 10 of them are running unopposed for the 2024 election cycle.  
        <p>Being that this was happening in my district for the first time I have ever seen when voting I decided I would step up and oppose if it happened again for the 2024 cycle.  District 9 is my district and no other candidate has stepped up to oppose so here I am now.  Sticking to my promise to myself I reached out to a third party that I will not mention here for guidance in the summer of 2024.  That party responded, but not until December 16th.  Right after that I was ill for about 3 weeks with a Christmas cold so I didn't get started until early January.  I am definitely new to the process of getting qualified for the November 2024 ballot.  The first thing I had to do was file a Designation of Treasurer Form with the Secretary of State's office.  For an independent candidate like myself that is form 30D.  Let me tell you this was no easy feat because if you want to be able to fundraise for a campaign for any public office you need to be able to open up a business account.  It was also advised by my secret mentor that I should not be my own treasurer.</p>
        <p>So the hunt for a treasurer was the first hurdle I had to get over.  I called around, and asked around to a lot of locat accountants and law offices and many stated they did not want to get involved in a political campaign because of the tight scrutiny involved.  It took about 3 weeks to find one that suited my need.  I am grateful he offered to take on the role.  Without him I wouldn't have been able to get too far into this process.</p>
        <p>Once I had my treasurer I had to file my form with the Secretary of State's office.  At that point I was able to begin my petitioning process which was on January 27th.  On that day it was a Saturday.  The weather was not so great for going out petitioning.  It was cold with off and on snow flurries.  The daytime high was 38 degrees and the low for the day was 22.  Sunset was 4:40pm.  Luckily there were a few friends and neighbors nearby I knew who were willing to help me get my first five signatures.  For an independent candidate in District 9 for Ohio Statehouse you need a minimum of 345 signatures and you need them before the deadline of March 18, 2024.  This was the day before the spring primary.</p>
        <p>I quickly realized that this was going to be something I was going to have to work at every day the weather was nice enough to go out.  Being that I have a regular 8:00am to 4:30pm job like most people my times to go out would be limited.  So this became my mission for the next 90 days.  Early on I could only go out between 4:30pm and 5:00pm or 5:15pm because that was how much light there was in the beginning with the short winter days.  Early on my daily average was about 4-5 signatures a day.  As I developed my door speech and the weeks went by I could go out longer.  Some of the best days to petition were on Saturdays and Sundays because I had the entire day to go out and knock on as many doors as I could get to in that time.</p>
        <p>It was a good time, but it was a lot of hard work and very physical for a middle aged lady.  I actually enjoyed petitioning much more than I expected.  It was a pleasure to get to meet so many amazing neighbors and community members I had never had the opportunity to brush shoulders with previously.  We had some great conversations, and even some healthy debates.  I heard personal stories of frustration, as well as stories with happy endings.  What I learned most about my community is that it has become extremely diverse in the past 15 years.  </p>
        <p>There are people from all walks of life, and religious backgrounds.  We have Hindus, Christians, Moslems, and even Buddhists that live and worship in this community.  We have Asian families, Indian families, Somali families, Hispanic and families of many other African nations here.  District 9 has all of these people as well as its native born American families.  We have become quite the little New York City here and it means there is so much potential to rebuild the community and better get to know our neighbors here.  I am excited about the prospect.</p>    
    </article>
</template>
