<template>
    <article class="blog-article">
        <h1>Journey to the Statehouse</h1>
        <i>Part 3</i>
        <p>As I continued moving through the petitioning process it took a little work to get a business set up and a business account opened.  Infact, Chase bank no longer opens up PAC accounts.  I had to go with Kemba.  My treasurer had to make two separate trips to banks on different weekends for us to get that ball rolling.  </p>
        <p>During my first days of petitioning I didn't have any flyers made yet and that was one of the things people really wanted was a flyer.  There were many doors I knocked on that people didn't want to make a decision to sign my petition because they didn't understand that signing the petition was not a commitment to vote for me at that moment.  There were some voters that simply did not sign because they wanted to stay off of the radar for potential jury duty which I understood, but had a chuckle about it.</p>
        <p>Others wanted to decide for themselves that I was affiliated with this party or that party.  It is a shame that people want to decide for the rest of the community in this way whether or not to allow someone to challenge the current incumbent.  This is a symptom of the current extreme divide now happening in our two party system.  This is the very reason why we need more than just two viable parties.  I finally took the stance with that push back that if nothing else we need to attempt to hold those in public office accountable for the decisions they are making for us.  Even if I don't get on the ballot or elected it sends a message that we aren't asleep at the wheel in our community and our district.  Simply signing a petition is not a commitment to vote for that person.</p>
        <p>About two weeks in I had a flyer made up, but it was rough around the edges.  I had a donation bullet point on there that did not work so well because my bank account was not ready and my website wasn't ready to accept donations.  One thing you learn early on is nothing seemingly goes according to the way you have it in your mind.  You just take the lessons and you build on them to make things better as you go.  I also had the campaign phone number on the first flyer, but it seemed like it would be better to have the campaign email as the best point of contact at this stage.  </p>
        <p>Once I made those decisions I changed up my flyer.  When I changed up my flyer I took off the donation bullet point and added instead just the campaign email and a QR code with my photo for the campaign website.  This flyer worked out nicely.  By this point in my petitioning process I had knocked on enough doors and spoken to enough voters to really be able to get a good grasp of what matters most to my community which has helped me to shape my campaign platform for District 9 Statehouse.</p>
        <p>As I was knocking on doors I noticed a lot of people didn't want to answer their doors because they had ring cameras to look through to decide if I was worthy of their time.  I started leaving messages on the ring door bells if for no other reason to let people in the community know I am out there running.  Then I came up with a really great idea.  Doorhangers!  I had about 500 of them made up and that was the best idea because it allowed people to not answer my door, check out my information, and make a decision as to whether or not they wanted me to come back to sign.</p>
        <p>I had great success with this.  One door hanger could lead to multiple signatures in one location.  In fact, late in my petitioning process I was invited into a voter's home and she invited several of her neighbors over to meet me and we had the most amazing two hours of getting to know one another.  Had I had the door hangers earlier I would have definitely had more than the 418 signatures I ended up with on March 14th when I decided to go ahead and file.  There is an $85 filing fee to turn in your petitions at the board of elections which is where you go in your respective county.</p>
        <p>I also had to quit petitioning a week earlier than I had intended because I ended up busting a toenail which became infected from all of the walking for hours every day.  My best day of signatures was on the last Saturday.  I was able to go out in the Sunbury Woods community.  That day I ended up with 35 signitatures going out between 11:00am and 5:30pm.  My worst day of signature collection was 2 on a Wednesday night.  The crazy thing about it was that it seemed the worse the weather was the higher my signature numbers were.  One Friday night I ended up with 10 signatures in just a few hours because it started to snow really hard.</p>
        <p>I think if I had had my door hangers sooner and hadn't busted my toe late in the game I could have probably ended up with around 575 signatures.  Of the 418 my secret mentor helped me a few afternoons and was able to gain me an additional 15 so I thank him for that.  Now it is just a waiting game to see if the board of elections is able to approve at least 345 of the 418 I turned in before the March 18th deadline.  Crossing my fingers we should know by May 31st whether or not Ohio Statehouse District 9 has a challenger to our incumbent Munira Abdullahi.  </p>
        <p>I have a few pointers for anyone else in the other 9 unopposed Franklin County Ohio Statehouse districts.  Don't be afraid to go out there and try it if you are really serious about being a part of a healthy and properly functioning government.  Our republic doesn't work without our willingness to make a commitment no matter the end result.  If nothing else you are helping to spark an important conversation that must be had in your community.  Secondly, when petitioning in adverse weather, don't risk snowy and icy porches.  I spent one Saturday attempting to hit communities in the eastern part of my district and I almost slipped and fell about 3 times before I decided to quit and not push my luck any further that day.</p>
        <p>Also, the local library is a great place to pick up signatures.  It is a little less personal, but I did that on another snowy Saturday for safety reasons.  I didn't want to lose any more valuable petitioning time due to weather.  The thing you have to be careful of when using a library is that not everyone that you talk to lives in your district so be vigilant and ask.  And finally, it is the rule that a person must be a registered voter at that address in your district for at least one year so always ask those two questions before getting too far with them.  This keeps your petition honest.</p>
        <p>Should I not get the official approval from the Franklin County Board of Elections on May 31st I may still file to run as a write in candidate.  Keep visiting this website for future updates and happenings with the most current status of the campaign. When the donation page is fully operational and if you would like to make a donation it would definitely help in gearing up for the next phase of this process and journey.  Thank you for joining me at the blog on this fascinating journey together.</p>
    </article>
</template>
