<template>
    <article class="blog-article">
        <h1>Journey to the Statehouse</h1>
        <i>Part 2</i>
            <p>During my 90 day journey I was constantly researching and reading and finding myself going to little trainings that my secret mentor invited me to participate in while obtaining signatures.  One night I was invited to go to a dinner showcasing one of the Libertarian candidates running for president who is from Florida.  He was looking to get his own signatures.  While at that dinner I met an older fellow who was a seasoned full-time petitioner for the Libertarian party.  I also met another man running as an Independent in District 2 for the Ohio Statehouse who was also in the petitioning process.</p>
            <p>That was an awesome evening of networking and learning about other people's challenges and how they came to be running for public offices.  About a week or two later I was invited to go to a training session by the Libertarian party.  A few days before I was supposed to attend I received a random email from a grassroots segment of the Republican party who was also having a training for running for office.  What I didn't realize was they didn't know that they had accidentally sent an invite to an Independent candidate.  At first they were a little shocked that I showed up to their private zoom party, but it turned out to be a good thing for me and for them.</p>
            <p>They actually invited me to attend their next committee meeting session in Dublin which was a great experience to have for someone who is new to the process and learning the ropes.   I had the opportunity to see all 3 Republican Senate candidates speak before the primary.  Unfortunately, if someone is not politically active in the community there is little local reporting on the evening news about the happenings of local politics or events or the who is who.  I actually find that to be a disservice to the local Ohio community.  This is something that needs work.  The public needs to feel like it is more included and able to be more engaged in our local government and at the state level.  Perhaps we would have more choices in the voting booth if there was more local news media engagement on a more regular basis.  24 hour news channels and social media have really distanced the public from the process in the past 30 years.  Their focus tends only to be on national politics when the real power in our Constitutional Republic is designed to come from the bottom up rather than the top down.</p>
            <p>While attending trainings and committee meetings I also took some time to visit some of my local township community meetings.  I really wanted to get a feel for the local governance happening here in District 9 outside of Forrest Park which is the section that I live in.  As my journey to the Statehouse moves forward I plan on visiting these local government sessions again as my campaign hopes become more official.</p>
    </article>
</template>
